services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Slub\SlubProfileBooked\:
    resource: '../Classes/*'

  Slub\SlubProfileBooked\Http\Request:
    public: true

  Slub\SlubProfileBooked\Routing\UriGenerator:
    public: true

  Slub\SlubProfileBooked\Service\BookedService:
    public: true
